### ISSUE TITLE
I want to put my application icon same as whatsapp,messanger in the contact in android how it can we possible. Please help me.

### ISSUE THREAD

**Issue by JineshSharma** [activesince93/ContentProvider#1]
![screenshot](https://cloud.githubusercontent.com/assets/26996206/24790148/9caa446e-1b93-11e7-8103-a43db3e9b513.png)

**Comment by activesince93** [comment]
Currently this repository does not contain code for the issue that you have stated. 

For that [SyncAdapter](https://developer.android.com/training/sync-adapters/creating-sync-adapter.html) may come handy to you. [Here](http://stackoverflow.com/questions/21701017/display-the-app-icon-if-the-contact-is-associated-with-the-application-in-phone) is the link that may help you.
